'milestone 1', alright, now this just needs more testing and refinement

diff --git a/helpers/osxcross-wizard b/helpers/osxcross-wizard
--- a/helpers/osxcross-wizard
+++ b/helpers/osxcross-wizard
@@ -7,9 +7,20 @@ ITSETUP_OXW_DIR="`dirname $ITSETUP_OXW_DIR`"
 osxcross_checkpath="$1"
 shift
 
+characterize() {
+	eval "`"$ITSETUP_OXW_DIR/osxcross_bin/osxcross-conf"`"
+	if [ "$OSXCROSS_TARGET" = "" ]; then
+		echo "unable to characterize: osxcross-conf did not successfully supply OSXCROSS_TARGET"
+		exit 1
+	fi
+	echo " OSXCROSS_TARGET=$OSXCROSS_TARGET"
+	echo "$OSXCROSS_TARGET" > "$ITSETUP_OXW_DIR/osxcross.target"
+}
+
 # do we already have this set?
 if "$ITSETUP_OXW_DIR/osxcross_bin/osxcross" >/dev/null 2>/dev/null ; then
 	echo " cached osxcross_bin: `readlink "$ITSETUP_OXW_DIR/osxcross_bin"`"
+	characterize
 	exit
 fi
 
@@ -22,6 +33,7 @@ test_candidate() {
 	if "$1/osxcross" >/dev/null 2>/dev/null ; then
 		echo " $2 osxcross found at: $1"
 		ln -s -T "$1" "$ITSETUP_OXW_DIR/osxcross_bin"
+		characterize
 		exit
 	fi
 }
diff --git a/test/b b/test/b
--- a/test/b
+++ b/test/b
@@ -1,17 +1,34 @@
 #!/bin/sh -e
-cd ..
-./setup --install scout_i386=on
+../setup --install scout_i386=on
 echo "(passed install)"
-cd test
+
+rm -rf build
+mkdir -p build
 
 do_variant() {
-	rm -rf "build_$1"
-	meson setup "build_$1" --cross-file "$1" ; meson compile -C "build_$1"
+	meson setup "build/$1" --cross-file "$1" > "build/$1_setup.log" || (echo "error in setup $1" ; exit 1)
+	meson compile -C "build/$1"
 }
 
-do_variant ivt_wx32_none
-do_variant ivt_wx32_staticstl
-do_variant ivt_wx64_none
-do_variant ivt_wx64_staticstl
+# Test most things reasonably available to Ubuntu 24.04.
+# (We can't pull in aarch64 Windows.)
 
-do_variant ivt_lgx32_stl_scout
+do_variant ivt_lgx32_default_scout
+do_variant ivt_lgx32_static_scout
+do_variant ivt_lgx32_zero_scout
+
+do_variant ivt_wx32_default
+do_variant ivt_wx32_static
+do_variant ivt_wx32_zero
+
+do_variant ivt_wx64_default
+do_variant ivt_wx64_static
+do_variant ivt_wx64_zero
+
+do_variant ivt_mx64_default
+do_variant ivt_mx64_static
+do_variant ivt_mx64_zero
+
+do_variant ivt_ma64_default
+do_variant ivt_ma64_static
+do_variant ivt_ma64_zero
