demolish the shell script idea in favour of auto-compiling C++

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -1,6 +1,5 @@
 #!/bin/sh -e
 
-ITSETUP_VER="version 0.0r1"
 if [ "$BASH_SOURCE" != "" ]; then
 	# if we're being invoked by bash, use BASH_SOURCE
 	ITSETUP_WHERE="`readlink -e "$BASH_SOURCE"`"
@@ -8,44 +7,13 @@ else
 	# alright, bet on zsh then
 	ITSETUP_WHERE="`readlink -e "$0"`"
 fi
-ITSETUP_DIR="`dirname $ITSETUP_WHERE`"
+export ITSETUP_DIR="`dirname $ITSETUP_WHERE`"
 
-# core library/structure
-
-itsetup_printvar() {
-	eval "echo \"$1=\$$1\""
+setupcore_build() {
+	meson setup "$ITSETUP_DIR/build" "$ITSETUP_DIR"
+	meson compile -C "$ITSETUP_DIR/build"
 }
 
-itsetup_whatami() {
-	echo "ivorytower-setup $ITSETUP_VER"
-	itsetup_printvar ITSETUP_WHERE
-	itsetup_printvar ITSETUP_DIR
+setupcore_build > "$ITSETUP_DIR/setupcore_build.log" || (echo "Error during ivorytower setup, check setupcore_build.log" ; exit 1)
 
-	echo
-}
-
-# general stuff
-
-. "$ITSETUP_DIR/res/crosssys.sh"
-. "$ITSETUP_DIR/res/config.sh"
-. "$ITSETUP_DIR/res/compsys.sh"
-
-# components
-
-. "$ITSETUP_DIR/res/z_steamrt.sh"
-
-# arg parser. would be nice to have this as a separate thing but *shrugs*
-while [ "$#" -gt 0 ]; do
-	ITSETUP_ARG="$1"
-	if eval "\"arg_$1\""; then
-		if [ "$ITSETUP_EXIT_STATUS" != "" ]; then
-			exit "$ITSETUP_EXIT_STATUS"
-		fi
-	else
-		echo "'$1' failed to parse, consider: $0 help"
-		exit 1
-	fi
-	shift
-done
-
-itsetup_runner
+exec "$ITSETUP_DIR/build/setupcore" "$@"
